apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubernetes
        image: kubercontaineracr.azurecr.io/kubernetes:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_HOST
          value: "mysqlkubernetes.mysql.database.azure.com" #Update here
        - name: DATABASE_USERNAME
          value: "georgebergson"  #Update here
        - name: DATABASE_PASSWORD
          value: "f0741jmgFK@"  #Update here
        - name: DATABASE_NAME
          value: "kubernete"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - kubernetes
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: php-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: kubernetes