<div class="container">
    <div class="row">
        <h3 class="fw-bold mb-4">Notícias para empresas que querem exportar</h3>
        <div class="col-md-8 mb-4">
            <a href="#">
                <img src="http://localhost:8888/gth/wp-content/uploads/2022/04/navio-container.png" class="img-fluid">
            </a>
        </div>
        <div class="col-md-4 mb-4">
            <a href="#">
                <img src="http://localhost:8888/gth/wp-content/uploads/2022/04/moca.png" class="img-fluid">
            </a>
        </div>
        <div class="col-md-4 mb-4">
            <a href="#">
                <img src="http://localhost:8888/gth/wp-content/uploads/2022/04/senhora.png" class="img-fluid">
            </a>
        </div>
        <div class="col-md-4 mb-4">
            <a href="#">
                <img src="http://localhost:8888/gth/wp-content/uploads/2022/04/cidade.png" class="img-fluid">
            </a>
        </div>
        <div class="col-md-4 mb-4">
            <a href="#">
                <img src="http://localhost:8888/gth/wp-content/uploads/2022/04/moco.png" class="img-fluid">
            </a>
        </div>
    </div>
</div>